{
 "title": "Weer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "station",
    "label": "Station",
    "query": "label_values(buienradar_temperature_c, station)"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(buienradar_temperature_c{station=~\"$station\"}[10m])",
     "legendFormat": "{{ station }}"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "mm/h" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(buienradar_rain_mmph{station=~\"$station\"}[10m])",
     "legendFormat": "{{ station }}"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(buienradar_windspeed_ms{station=~\"$station\"}[10m])",
     "legendFormat": "{{ station }}"
    }
   ]
  },
  {
   "title": "Solar Radiation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Wm2" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(buienradar_sunintensity_mw2{station=~\"$station\"}[10m])",
     "legendFormat": "{{ station }}"
    }
   ]
  },
  {
   "title": "Wind Speed (Bft)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bft" }
   ],
   "targets": [
    {
     "expr": "buienradar_windspeed_bft{station=~\"$station\"}",
     "legendFormat": "{{ station }}"
    }
   ]
  },
  {
   "title": "Wind Gusts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(buienradar_windgust_ms{station=~\"$station\"}[10m])",
     "legendFormat": "{{ station }}"
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(buienradar_sight_m{station=~\"$station\"}[10m])",
     "legendFormat": "{{ station }}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(buienradar_pressure_hpa{station=~\"$station\"}[10m])",
     "legendFormat": "{{ station }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(buienradar_humidity_pct{station=~\"$station\"}[10m])",
     "legendFormat": "{{ station }}"
    }
   ]
  }
 ]
}